-- BlueprintAI MySQL Schema Migration 001
-- Aligned with Business Transformation AI Requirements & Data Model (Chaos2Commit 2026)

CREATE DATABASE IF NOT EXISTS `compile_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `compile_db`;

-- 1. Organizations
CREATE TABLE IF NOT EXISTS `organizations` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Workspaces
CREATE TABLE IF NOT EXISTS `workspaces` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `org_id` CHAR(36) NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_workspaces_org` FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Users
CREATE TABLE IF NOT EXISTS `users` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `workspace_id` CHAR(36) NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` VARCHAR(50) NOT NULL DEFAULT 'member', -- owner, admin, member, viewer
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_users_email` (`email`),
  CONSTRAINT `fk_users_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Sessions (Blueprint intake & reasoning sessions)
CREATE TABLE IF NOT EXISTS `sessions` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `workspace_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `title` VARCHAR(255) NOT NULL DEFAULT 'Untitled Blueprint',
  `status` VARCHAR(50) NOT NULL DEFAULT 'intake', -- intake, discovery, generating, completed, archived
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sessions_workspace` (`workspace_id`),
  INDEX `idx_sessions_user` (`user_id`),
  CONSTRAINT `fk_sessions_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Input Documents (Uploaded SOPs, PDFs, PPTXs, DOCXs, or pasted raw input)
CREATE TABLE IF NOT EXISTS `input_documents` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `session_id` CHAR(36) NOT NULL,
  `file_name` VARCHAR(255) NULL,
  `file_type` VARCHAR(50) NOT NULL, -- text, pdf, docx, pptx, transcript
  `storage_url` VARCHAR(500) NULL,
  `parsed_text` LONGTEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_docs_session` (`session_id`),
  CONSTRAINT `fk_docs_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Business Context (Normalized context object distilled by Ingestion layer)
CREATE TABLE IF NOT EXISTS `business_contexts` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `session_id` CHAR(36) NOT NULL UNIQUE,
  `goals` TEXT NULL,
  `constraints_text` TEXT NULL,
  `stakeholders` TEXT NULL,
  `existing_systems` TEXT NULL,
  `raw_summary` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_ctx_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. Discovery Q&A (AI Business Consultant clarifying questions, max 5-7 per session)
CREATE TABLE IF NOT EXISTS `discovery_qas` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `session_id` CHAR(36) NOT NULL,
  `question` TEXT NOT NULL,
  `answer` TEXT NULL,
  `order_index` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(50) NOT NULL DEFAULT 'pending', -- pending, answered, skipped
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `answered_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `idx_qa_session` (`session_id`),
  CONSTRAINT `fk_qa_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. Business Requirement Documents (BRD generated by Business Analysis Engine)
CREATE TABLE IF NOT EXISTS `brds` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `session_id` CHAR(36) NOT NULL,
  `objectives` TEXT NULL,
  `scope` TEXT NULL,
  `stakeholders_list` JSON NULL,
  `gap_analysis` JSON NULL,
  `functional_requirements` JSON NULL,
  `non_functional_requirements` JSON NULL,
  `assumptions` JSON NULL,
  `constraints_data` JSON NULL,
  `version` INT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_brd_session` (`session_id`),
  CONSTRAINT `fk_brd_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. Solution Architectures (HLD, Tech Stack, and Security Notes)
CREATE TABLE IF NOT EXISTS `solution_architectures` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `session_id` CHAR(36) NOT NULL,
  `hld_summary` TEXT NULL,
  `tech_stack` JSON NULL, -- [{ category, choice, rationale }]
  `components` JSON NULL, -- [{ name, responsibility, tech }]
  `data_flow` TEXT NULL,
  `security_notes` TEXT NULL,
  `version` INT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sa_session` (`session_id`),
  CONSTRAINT `fk_sa_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. Effort Estimates (AI Planning Engine effort & rough cost band)
CREATE TABLE IF NOT EXISTS `effort_estimates` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `session_id` CHAR(36) NOT NULL,
  `phase_breakdown` JSON NULL, -- [{ phase, weeks, percentage }]
  `cost_band` VARCHAR(100) NULL, -- Low: $28k | Mid: $45k | High: $68k
  `low_estimate_usd` INT NULL DEFAULT 0,
  `mid_estimate_usd` INT NULL DEFAULT 0,
  `high_estimate_usd` INT NULL DEFAULT 0,
  `team_assumptions` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_est_session` (`session_id`),
  CONSTRAINT `fk_est_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. Exports (Export layer - PDF, Word, JSON)
CREATE TABLE IF NOT EXISTS `exports` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `session_id` CHAR(36) NOT NULL,
  `format` VARCHAR(50) NOT NULL, -- pdf, docx, json
  `file_url` VARCHAR(500) NOT NULL,
  `file_size_bytes` INT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_exports_session` (`session_id`),
  CONSTRAINT `fk_exports_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. Session Versions (Version History tracking edits & single-section regenerations)
CREATE TABLE IF NOT EXISTS `session_versions` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `session_id` CHAR(36) NOT NULL,
  `version_number` INT NOT NULL DEFAULT 1,
  `changed_section` VARCHAR(100) NOT NULL, -- brd, architecture, estimate, user_edit
  `snapshot_data` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_versions_session` (`session_id`),
  CONSTRAINT `fk_versions_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. Session Messages (Conversational AI Memory for multi-turn Discovery Q&A)
CREATE TABLE IF NOT EXISTS `session_messages` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `session_id` CHAR(36) NOT NULL,
  `sender` VARCHAR(50) NOT NULL DEFAULT 'user', -- user, ai, consultant
  `message_text` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_msg_session` (`session_id`),
  CONSTRAINT `fk_msg_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
